
version: "3.2"

networks:
  sampleSorter:

services:
  frontend:
    build: frontend

    ports:
      - "80:3000"

#  worker:
#    build: worker


  sorter:
    build: sorter
    ports:
      - "5000:5000"