---
version: "3.2"

services:
  worker_1:
    volumes:
      - "./worker/src:/code"

  worker_2:
    volumes:
      - "./worker/src:/code"

  worker_3:
    volumes:
      - "./worker/src:/code"

  sorter:
    volumes:
      - "./sorter/src:/code"