
version: "3.2"

networks:
  sampleSorter:

services:
  frontend:
    build: frontend
    ports:
      - "80:3000"
    env_file:
      - ./default.env

  worker_1:
    build: worker
    environment:
      NAME: worker_1
    env_file:
      - ./default.env

  worker_2:
    build: worker
    environment:
      NAME: worker_2
    env_file:
      - ./default.env

  worker_3:
    build: worker
    environment:
      NAME: worker_3
    env_file:
      - ./default.env

  sorter:
    build: sorter
    ports:
      - "5000:5000"
    env_file:
      - ./default.env